# Generated by Django 4.0.3 on 2022-03-08 00:00

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('logradouro', models.CharField(db_column='LOGRADOURO', max_length=100)),
                ('cep', models.CharField(db_column='CEP', max_length=9)),
                ('bairro', models.CharField(db_column='BAIRRO', max_length=25)),
                ('cidade', models.CharField(db_column='CIDADE', max_length=30)),
                ('uf', models.CharField(db_column='UF', max_length=2)),
            ],
            options={
                'verbose_name': 'endereco',
                'verbose_name_plural': 'enderecos',
                'db_table': 'ENDERECO',
            },
        ),
    ]
