# Generated by Django 4.0.3 on 2022-03-14 23:35

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('titulo', models.CharField(db_column='TITULO', max_length=100)),
                ('tipo', models.CharField(db_column='TIPO', max_length=100)),
                ('numero', models.CharField(db_column='NUMERO', max_length=10)),
                ('endereco', models.OneToOneField(db_column='ENDERECO', on_delete=django.db.models.deletion.DO_NOTHING, to='endereco.endereco')),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locais',
                'db_table': 'LOCAL',
            },
        ),
    ]
